language: java
install: true

os: linux
dist: trusty
jdk: openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: build
      name: Build
      script: ./gradlew assemble

    - stage: test
      name: Test
      services: postgresql
      before_script:
        - psql -U postgres -c "CREATE USER cirrocumulus_registry WITH SUPERUSER PASSWORD 'cirrocumulus_registry';"
        - psql -U postgres -c "CREATE DATABASE cirrocumulus_registry OWNER cirrocumulus_registry;"
      script: ./gradlew check
