version: "3"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cirrocumulus_registry
      POSTGRES_USER: cirrocumulus_registry
      POSTGRES_PASSWORD: cirrocumulus_registry
